### ISSUE TITLE
Add ability to change the order of cards w/out having to move around big blocks of YAML

### ISSUE THREAD

**Issue by jocassid** [jocassid/homepage#8]
Add ability to change the order of cards w/out having to move around big blocks of YAML.  Want some element to contain cards and specify their order

maybe something like:

```yaml
- type: cards
- order:
  - food
  - productivity
- contents:
  - card: food
    - href
```
